/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Mock } from "./ERC20Mock";
export type { MockGnosisConditionalTokens } from "./MockGnosisConditionalTokens";
export type { MockUMAOptimisticOracle } from "./MockUMAOptimisticOracle";
