/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockAllocationManager } from "./MockAllocationManager";
export type { MockDelegationManager } from "./MockDelegationManager";
export type { MockGnosisConditionalTokens } from "./MockGnosisConditionalTokens";
export type { MockSlashingCoordinator } from "./MockSlashingCoordinator";
export type { MockUMAOptimisticOracle } from "./MockUMAOptimisticOracle";
