/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IGnosisConditionalTokensInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getConditionPayouts"
      | "getPayout"
      | "prepareCondition"
      | "reportPayouts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ConditionPreparation" | "PayoutReported"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getConditionPayouts",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayout",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "prepareCondition",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reportPayouts",
    values: [BytesLike, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getConditionPayouts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayout", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "prepareCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportPayouts",
    data: BytesLike
  ): Result;
}

export namespace ConditionPreparationEvent {
  export type InputTuple = [
    conditionId: BytesLike,
    oracle: AddressLike,
    questionId: BytesLike,
    outcomeSlotCount: BigNumberish
  ];
  export type OutputTuple = [
    conditionId: string,
    oracle: string,
    questionId: string,
    outcomeSlotCount: bigint
  ];
  export interface OutputObject {
    conditionId: string;
    oracle: string;
    questionId: string;
    outcomeSlotCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutReportedEvent {
  export type InputTuple = [conditionId: BytesLike, payouts: BigNumberish[]];
  export type OutputTuple = [conditionId: string, payouts: bigint[]];
  export interface OutputObject {
    conditionId: string;
    payouts: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IGnosisConditionalTokens extends BaseContract {
  connect(runner?: ContractRunner | null): IGnosisConditionalTokens;
  waitForDeployment(): Promise<this>;

  interface: IGnosisConditionalTokensInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getConditionPayouts: TypedContractMethod<
    [conditionId: BytesLike],
    [[boolean, bigint[]] & { resolved: boolean; payouts: bigint[] }],
    "view"
  >;

  getPayout: TypedContractMethod<
    [conditionId: BytesLike, outcomeSlot: BigNumberish],
    [bigint],
    "view"
  >;

  prepareCondition: TypedContractMethod<
    [
      oracle: AddressLike,
      questionId: BytesLike,
      outcomeSlotCount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  reportPayouts: TypedContractMethod<
    [conditionId: BytesLike, payouts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getConditionPayouts"
  ): TypedContractMethod<
    [conditionId: BytesLike],
    [[boolean, bigint[]] & { resolved: boolean; payouts: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPayout"
  ): TypedContractMethod<
    [conditionId: BytesLike, outcomeSlot: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "prepareCondition"
  ): TypedContractMethod<
    [
      oracle: AddressLike,
      questionId: BytesLike,
      outcomeSlotCount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reportPayouts"
  ): TypedContractMethod<
    [conditionId: BytesLike, payouts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConditionPreparation"
  ): TypedContractEvent<
    ConditionPreparationEvent.InputTuple,
    ConditionPreparationEvent.OutputTuple,
    ConditionPreparationEvent.OutputObject
  >;
  getEvent(
    key: "PayoutReported"
  ): TypedContractEvent<
    PayoutReportedEvent.InputTuple,
    PayoutReportedEvent.OutputTuple,
    PayoutReportedEvent.OutputObject
  >;

  filters: {
    "ConditionPreparation(bytes32,address,bytes32,uint256)": TypedContractEvent<
      ConditionPreparationEvent.InputTuple,
      ConditionPreparationEvent.OutputTuple,
      ConditionPreparationEvent.OutputObject
    >;
    ConditionPreparation: TypedContractEvent<
      ConditionPreparationEvent.InputTuple,
      ConditionPreparationEvent.OutputTuple,
      ConditionPreparationEvent.OutputObject
    >;

    "PayoutReported(bytes32,uint256[])": TypedContractEvent<
      PayoutReportedEvent.InputTuple,
      PayoutReportedEvent.OutputTuple,
      PayoutReportedEvent.OutputObject
    >;
    PayoutReported: TypedContractEvent<
      PayoutReportedEvent.InputTuple,
      PayoutReportedEvent.OutputTuple,
      PayoutReportedEvent.OutputObject
    >;
  };
}
