/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGnosisConditionalTokens,
  IGnosisConditionalTokensInterface,
} from "../../../../protocol/contracts/interfaces/IGnosisConditionalTokens";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "conditionId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "oracle",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "questionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "outcomeSlotCount",
        type: "uint256",
      },
    ],
    name: "ConditionPreparation",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "conditionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payouts",
        type: "uint256[]",
      },
    ],
    name: "PayoutReported",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "conditionId",
        type: "bytes32",
      },
    ],
    name: "getConditionPayouts",
    outputs: [
      {
        internalType: "bool",
        name: "resolved",
        type: "bool",
      },
      {
        internalType: "uint256[]",
        name: "payouts",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "conditionId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "outcomeSlot",
        type: "uint256",
      },
    ],
    name: "getPayout",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "oracle",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "questionId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "outcomeSlotCount",
        type: "uint256",
      },
    ],
    name: "prepareCondition",
    outputs: [
      {
        internalType: "bytes32",
        name: "conditionId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "conditionId",
        type: "bytes32",
      },
      {
        internalType: "uint256[]",
        name: "payouts",
        type: "uint256[]",
      },
    ],
    name: "reportPayouts",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGnosisConditionalTokens__factory {
  static readonly abi = _abi;
  static createInterface(): IGnosisConditionalTokensInterface {
    return new Interface(_abi) as IGnosisConditionalTokensInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGnosisConditionalTokens {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IGnosisConditionalTokens;
  }
}
