[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.26"

remappings = [
	"@openzeppelin/=lib/openzeppelin-contracts/"
]

[fmt]
line_length = 100
multiline_func_header = "all"
