/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface SlashingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addStake"
      | "removeStake"
      | "setAVS"
      | "slash"
      | "stake"
      | "totalSlashed"
      | "veyraOracleAVS"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AVSUpdated"
      | "Slashed"
      | "StakeAdded"
      | "StakeRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addStake",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeStake",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setAVS", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "slash",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "totalSlashed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "veyraOracleAVS",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAVS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "slash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSlashed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "veyraOracleAVS",
    data: BytesLike
  ): Result;
}

export namespace AVSUpdatedEvent {
  export type InputTuple = [avs: AddressLike];
  export type OutputTuple = [avs: string];
  export interface OutputObject {
    avs: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlashedEvent {
  export type InputTuple = [operator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [operator: string, amount: bigint];
  export interface OutputObject {
    operator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeAddedEvent {
  export type InputTuple = [operator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [operator: string, amount: bigint];
  export interface OutputObject {
    operator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeRemovedEvent {
  export type InputTuple = [operator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [operator: string, amount: bigint];
  export interface OutputObject {
    operator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Slashing extends BaseContract {
  connect(runner?: ContractRunner | null): Slashing;
  waitForDeployment(): Promise<this>;

  interface: SlashingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addStake: TypedContractMethod<
    [operator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeStake: TypedContractMethod<
    [operator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAVS: TypedContractMethod<[avs_: AddressLike], [void], "nonpayable">;

  slash: TypedContractMethod<
    [operator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalSlashed: TypedContractMethod<[], [bigint], "view">;

  veyraOracleAVS: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addStake"
  ): TypedContractMethod<
    [operator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeStake"
  ): TypedContractMethod<
    [operator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAVS"
  ): TypedContractMethod<[avs_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slash"
  ): TypedContractMethod<
    [operator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSlashed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "veyraOracleAVS"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AVSUpdated"
  ): TypedContractEvent<
    AVSUpdatedEvent.InputTuple,
    AVSUpdatedEvent.OutputTuple,
    AVSUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Slashed"
  ): TypedContractEvent<
    SlashedEvent.InputTuple,
    SlashedEvent.OutputTuple,
    SlashedEvent.OutputObject
  >;
  getEvent(
    key: "StakeAdded"
  ): TypedContractEvent<
    StakeAddedEvent.InputTuple,
    StakeAddedEvent.OutputTuple,
    StakeAddedEvent.OutputObject
  >;
  getEvent(
    key: "StakeRemoved"
  ): TypedContractEvent<
    StakeRemovedEvent.InputTuple,
    StakeRemovedEvent.OutputTuple,
    StakeRemovedEvent.OutputObject
  >;

  filters: {
    "AVSUpdated(address)": TypedContractEvent<
      AVSUpdatedEvent.InputTuple,
      AVSUpdatedEvent.OutputTuple,
      AVSUpdatedEvent.OutputObject
    >;
    AVSUpdated: TypedContractEvent<
      AVSUpdatedEvent.InputTuple,
      AVSUpdatedEvent.OutputTuple,
      AVSUpdatedEvent.OutputObject
    >;

    "Slashed(address,uint256)": TypedContractEvent<
      SlashedEvent.InputTuple,
      SlashedEvent.OutputTuple,
      SlashedEvent.OutputObject
    >;
    Slashed: TypedContractEvent<
      SlashedEvent.InputTuple,
      SlashedEvent.OutputTuple,
      SlashedEvent.OutputObject
    >;

    "StakeAdded(address,uint256)": TypedContractEvent<
      StakeAddedEvent.InputTuple,
      StakeAddedEvent.OutputTuple,
      StakeAddedEvent.OutputObject
    >;
    StakeAdded: TypedContractEvent<
      StakeAddedEvent.InputTuple,
      StakeAddedEvent.OutputTuple,
      StakeAddedEvent.OutputObject
    >;

    "StakeRemoved(address,uint256)": TypedContractEvent<
      StakeRemovedEvent.InputTuple,
      StakeRemovedEvent.OutputTuple,
      StakeRemovedEvent.OutputObject
    >;
    StakeRemoved: TypedContractEvent<
      StakeRemovedEvent.InputTuple,
      StakeRemovedEvent.OutputTuple,
      StakeRemovedEvent.OutputObject
    >;
  };
}
