/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface GnosisAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "conditionResolved"
      | "conditionToRequest"
      | "conditionalTokens"
      | "getConditionId"
      | "getRequestId"
      | "handleCondition"
      | "requestToCondition"
      | "resolveCondition"
      | "veyraOracleAVS"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ConditionHandled" | "ConditionResolved"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "conditionResolved",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "conditionToRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "conditionalTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getConditionId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleCondition",
    values: [BytesLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestToCondition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveCondition",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "veyraOracleAVS",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "conditionResolved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conditionToRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conditionalTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConditionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestToCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "veyraOracleAVS",
    data: BytesLike
  ): Result;
}

export namespace ConditionHandledEvent {
  export type InputTuple = [
    conditionId: BytesLike,
    requestId: BytesLike,
    questionId: BytesLike,
    outcomeSlotCount: BigNumberish
  ];
  export type OutputTuple = [
    conditionId: string,
    requestId: string,
    questionId: string,
    outcomeSlotCount: bigint
  ];
  export interface OutputObject {
    conditionId: string;
    requestId: string;
    questionId: string;
    outcomeSlotCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConditionResolvedEvent {
  export type InputTuple = [
    conditionId: BytesLike,
    requestId: BytesLike,
    outcome: boolean
  ];
  export type OutputTuple = [
    conditionId: string,
    requestId: string,
    outcome: boolean
  ];
  export interface OutputObject {
    conditionId: string;
    requestId: string;
    outcome: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GnosisAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): GnosisAdapter;
  waitForDeployment(): Promise<this>;

  interface: GnosisAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  conditionResolved: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  conditionToRequest: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  conditionalTokens: TypedContractMethod<[], [string], "view">;

  getConditionId: TypedContractMethod<[requestId: BytesLike], [string], "view">;

  getRequestId: TypedContractMethod<[conditionId: BytesLike], [string], "view">;

  handleCondition: TypedContractMethod<
    [
      conditionId: BytesLike,
      questionId: BytesLike,
      outcomeSlotCount: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  requestToCondition: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  resolveCondition: TypedContractMethod<
    [requestId: BytesLike, outcomeSlotCount: BigNumberish],
    [string],
    "nonpayable"
  >;

  veyraOracleAVS: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "conditionResolved"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "conditionToRequest"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "conditionalTokens"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getConditionId"
  ): TypedContractMethod<[requestId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRequestId"
  ): TypedContractMethod<[conditionId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "handleCondition"
  ): TypedContractMethod<
    [
      conditionId: BytesLike,
      questionId: BytesLike,
      outcomeSlotCount: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestToCondition"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "resolveCondition"
  ): TypedContractMethod<
    [requestId: BytesLike, outcomeSlotCount: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "veyraOracleAVS"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ConditionHandled"
  ): TypedContractEvent<
    ConditionHandledEvent.InputTuple,
    ConditionHandledEvent.OutputTuple,
    ConditionHandledEvent.OutputObject
  >;
  getEvent(
    key: "ConditionResolved"
  ): TypedContractEvent<
    ConditionResolvedEvent.InputTuple,
    ConditionResolvedEvent.OutputTuple,
    ConditionResolvedEvent.OutputObject
  >;

  filters: {
    "ConditionHandled(bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      ConditionHandledEvent.InputTuple,
      ConditionHandledEvent.OutputTuple,
      ConditionHandledEvent.OutputObject
    >;
    ConditionHandled: TypedContractEvent<
      ConditionHandledEvent.InputTuple,
      ConditionHandledEvent.OutputTuple,
      ConditionHandledEvent.OutputObject
    >;

    "ConditionResolved(bytes32,bytes32,bool)": TypedContractEvent<
      ConditionResolvedEvent.InputTuple,
      ConditionResolvedEvent.OutputTuple,
      ConditionResolvedEvent.OutputObject
    >;
    ConditionResolved: TypedContractEvent<
      ConditionResolvedEvent.InputTuple,
      ConditionResolvedEvent.OutputTuple,
      ConditionResolvedEvent.OutputObject
    >;
  };
}
