/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace VPOAdapter {
  export type RequestStruct = {
    marketRef: BytesLike;
    requester: AddressLike;
    data: BytesLike;
    fulfilled: boolean;
    attestationCid: BytesLike;
    outcome: boolean;
    metadata: BytesLike;
  };

  export type RequestStructOutput = [
    marketRef: string,
    requester: string,
    data: string,
    fulfilled: boolean,
    attestationCid: string,
    outcome: boolean,
    metadata: string
  ] & {
    marketRef: string;
    requester: string;
    data: string;
    fulfilled: boolean;
    attestationCid: string;
    outcome: boolean;
    metadata: string;
  };
}

export interface VPOAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "avsNodes"
      | "fulfillVerification"
      | "getFulfillment"
      | "getRequest"
      | "requestVerification"
      | "setAVSNode"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AVSNodeUpdated"
      | "VerificationFulfilled"
      | "VerificationRequested"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "avsNodes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillVerification",
    values: [BytesLike, BytesLike, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFulfillment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestVerification",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAVSNode",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "avsNodes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fulfillVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFulfillment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAVSNode", data: BytesLike): Result;
}

export namespace AVSNodeUpdatedEvent {
  export type InputTuple = [node: AddressLike, enabled: boolean];
  export type OutputTuple = [node: string, enabled: boolean];
  export interface OutputObject {
    node: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationFulfilledEvent {
  export type InputTuple = [
    requestId: BytesLike,
    attestationCid: BytesLike,
    outcome: boolean,
    metadata: BytesLike
  ];
  export type OutputTuple = [
    requestId: string,
    attestationCid: string,
    outcome: boolean,
    metadata: string
  ];
  export interface OutputObject {
    requestId: string;
    attestationCid: string;
    outcome: boolean;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRequestedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    requester: AddressLike,
    marketRef: BytesLike,
    data: BytesLike
  ];
  export type OutputTuple = [
    requestId: string,
    requester: string,
    marketRef: string,
    data: string
  ];
  export interface OutputObject {
    requestId: string;
    requester: string;
    marketRef: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VPOAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): VPOAdapter;
  waitForDeployment(): Promise<this>;

  interface: VPOAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  avsNodes: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  fulfillVerification: TypedContractMethod<
    [
      requestId: BytesLike,
      attestationCid: BytesLike,
      outcome: boolean,
      metadata: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFulfillment: TypedContractMethod<
    [requestId: BytesLike],
    [
      [boolean, string, boolean, string] & {
        exists: boolean;
        attestationCid: string;
        outcome: boolean;
        metadata: string;
      }
    ],
    "view"
  >;

  getRequest: TypedContractMethod<
    [requestId: BytesLike],
    [VPOAdapter.RequestStructOutput],
    "view"
  >;

  requestVerification: TypedContractMethod<
    [marketRef: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;

  setAVSNode: TypedContractMethod<
    [node: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "avsNodes"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "fulfillVerification"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      attestationCid: BytesLike,
      outcome: boolean,
      metadata: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getFulfillment"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [
      [boolean, string, boolean, string] & {
        exists: boolean;
        attestationCid: string;
        outcome: boolean;
        metadata: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [VPOAdapter.RequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestVerification"
  ): TypedContractMethod<
    [marketRef: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAVSNode"
  ): TypedContractMethod<
    [node: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AVSNodeUpdated"
  ): TypedContractEvent<
    AVSNodeUpdatedEvent.InputTuple,
    AVSNodeUpdatedEvent.OutputTuple,
    AVSNodeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationFulfilled"
  ): TypedContractEvent<
    VerificationFulfilledEvent.InputTuple,
    VerificationFulfilledEvent.OutputTuple,
    VerificationFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRequested"
  ): TypedContractEvent<
    VerificationRequestedEvent.InputTuple,
    VerificationRequestedEvent.OutputTuple,
    VerificationRequestedEvent.OutputObject
  >;

  filters: {
    "AVSNodeUpdated(address,bool)": TypedContractEvent<
      AVSNodeUpdatedEvent.InputTuple,
      AVSNodeUpdatedEvent.OutputTuple,
      AVSNodeUpdatedEvent.OutputObject
    >;
    AVSNodeUpdated: TypedContractEvent<
      AVSNodeUpdatedEvent.InputTuple,
      AVSNodeUpdatedEvent.OutputTuple,
      AVSNodeUpdatedEvent.OutputObject
    >;

    "VerificationFulfilled(bytes32,bytes,bool,bytes)": TypedContractEvent<
      VerificationFulfilledEvent.InputTuple,
      VerificationFulfilledEvent.OutputTuple,
      VerificationFulfilledEvent.OutputObject
    >;
    VerificationFulfilled: TypedContractEvent<
      VerificationFulfilledEvent.InputTuple,
      VerificationFulfilledEvent.OutputTuple,
      VerificationFulfilledEvent.OutputObject
    >;

    "VerificationRequested(bytes32,address,bytes32,bytes)": TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
    VerificationRequested: TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
  };
}
