/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace VPOOracleRelayer {
  export type AttestationStruct = {
    marketId: BytesLike;
    questionHash: BytesLike;
    outcome: BigNumberish;
    sourceId: string;
    expiresAt: BigNumberish;
    nonce: BigNumberish;
  };

  export type AttestationStructOutput = [
    marketId: string,
    questionHash: string,
    outcome: bigint,
    sourceId: string,
    expiresAt: bigint,
    nonce: bigint
  ] & {
    marketId: string;
    questionHash: string;
    outcome: bigint;
    sourceId: string;
    expiresAt: bigint;
    nonce: bigint;
  };
}

export interface VPOOracleRelayerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ATTESTATION_TYPEHASH"
      | "DOMAIN_SEPARATOR"
      | "admin"
      | "fulfillAttestation"
      | "getResult"
      | "isNonceUsed"
      | "requestResolve"
      | "setSigner"
      | "signers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttestationFulfilled"
      | "ResolveFulfilled"
      | "ResolveRequested"
      | "SignerUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ATTESTATION_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fulfillAttestation",
    values: [VPOOracleRelayer.AttestationStruct, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getResult",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isNonceUsed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestResolve",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSigner",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "signers",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ATTESTATION_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fulfillAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isNonceUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSigner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signers", data: BytesLike): Result;
}

export namespace AttestationFulfilledEvent {
  export type InputTuple = [
    marketId: BytesLike,
    signer: AddressLike,
    outcome: BigNumberish,
    ipfsCid: string
  ];
  export type OutputTuple = [
    marketId: string,
    signer: string,
    outcome: bigint,
    ipfsCid: string
  ];
  export interface OutputObject {
    marketId: string;
    signer: string;
    outcome: bigint;
    ipfsCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolveFulfilledEvent {
  export type InputTuple = [
    marketId: BytesLike,
    resultData: BytesLike,
    metadata: BytesLike
  ];
  export type OutputTuple = [
    marketId: string,
    resultData: string,
    metadata: string
  ];
  export interface OutputObject {
    marketId: string;
    resultData: string;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolveRequestedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    requester: AddressLike,
    extraData: BytesLike
  ];
  export type OutputTuple = [
    marketId: string,
    requester: string,
    extraData: string
  ];
  export interface OutputObject {
    marketId: string;
    requester: string;
    extraData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerUpdatedEvent {
  export type InputTuple = [signer: AddressLike, enabled: boolean];
  export type OutputTuple = [signer: string, enabled: boolean];
  export interface OutputObject {
    signer: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VPOOracleRelayer extends BaseContract {
  connect(runner?: ContractRunner | null): VPOOracleRelayer;
  waitForDeployment(): Promise<this>;

  interface: VPOOracleRelayerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ATTESTATION_TYPEHASH: TypedContractMethod<[], [string], "view">;

  DOMAIN_SEPARATOR: TypedContractMethod<[], [string], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  fulfillAttestation: TypedContractMethod<
    [
      attestation: VPOOracleRelayer.AttestationStruct,
      signature: BytesLike,
      ipfsCid: string
    ],
    [void],
    "nonpayable"
  >;

  getResult: TypedContractMethod<
    [marketId: BytesLike],
    [
      [boolean, string, string] & {
        resolved: boolean;
        resultData: string;
        metadata: string;
      }
    ],
    "view"
  >;

  isNonceUsed: TypedContractMethod<[nonce: BigNumberish], [boolean], "view">;

  requestResolve: TypedContractMethod<
    [marketId: BytesLike, extraData: BytesLike],
    [void],
    "nonpayable"
  >;

  setSigner: TypedContractMethod<
    [signer: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  signers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ATTESTATION_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DOMAIN_SEPARATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fulfillAttestation"
  ): TypedContractMethod<
    [
      attestation: VPOOracleRelayer.AttestationStruct,
      signature: BytesLike,
      ipfsCid: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getResult"
  ): TypedContractMethod<
    [marketId: BytesLike],
    [
      [boolean, string, string] & {
        resolved: boolean;
        resultData: string;
        metadata: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isNonceUsed"
  ): TypedContractMethod<[nonce: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestResolve"
  ): TypedContractMethod<
    [marketId: BytesLike, extraData: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSigner"
  ): TypedContractMethod<
    [signer: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "AttestationFulfilled"
  ): TypedContractEvent<
    AttestationFulfilledEvent.InputTuple,
    AttestationFulfilledEvent.OutputTuple,
    AttestationFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "ResolveFulfilled"
  ): TypedContractEvent<
    ResolveFulfilledEvent.InputTuple,
    ResolveFulfilledEvent.OutputTuple,
    ResolveFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "ResolveRequested"
  ): TypedContractEvent<
    ResolveRequestedEvent.InputTuple,
    ResolveRequestedEvent.OutputTuple,
    ResolveRequestedEvent.OutputObject
  >;
  getEvent(
    key: "SignerUpdated"
  ): TypedContractEvent<
    SignerUpdatedEvent.InputTuple,
    SignerUpdatedEvent.OutputTuple,
    SignerUpdatedEvent.OutputObject
  >;

  filters: {
    "AttestationFulfilled(bytes32,address,uint8,string)": TypedContractEvent<
      AttestationFulfilledEvent.InputTuple,
      AttestationFulfilledEvent.OutputTuple,
      AttestationFulfilledEvent.OutputObject
    >;
    AttestationFulfilled: TypedContractEvent<
      AttestationFulfilledEvent.InputTuple,
      AttestationFulfilledEvent.OutputTuple,
      AttestationFulfilledEvent.OutputObject
    >;

    "ResolveFulfilled(bytes32,bytes,bytes)": TypedContractEvent<
      ResolveFulfilledEvent.InputTuple,
      ResolveFulfilledEvent.OutputTuple,
      ResolveFulfilledEvent.OutputObject
    >;
    ResolveFulfilled: TypedContractEvent<
      ResolveFulfilledEvent.InputTuple,
      ResolveFulfilledEvent.OutputTuple,
      ResolveFulfilledEvent.OutputObject
    >;

    "ResolveRequested(bytes32,address,bytes)": TypedContractEvent<
      ResolveRequestedEvent.InputTuple,
      ResolveRequestedEvent.OutputTuple,
      ResolveRequestedEvent.OutputObject
    >;
    ResolveRequested: TypedContractEvent<
      ResolveRequestedEvent.InputTuple,
      ResolveRequestedEvent.OutputTuple,
      ResolveRequestedEvent.OutputObject
    >;

    "SignerUpdated(address,bool)": TypedContractEvent<
      SignerUpdatedEvent.InputTuple,
      SignerUpdatedEvent.OutputTuple,
      SignerUpdatedEvent.OutputObject
    >;
    SignerUpdated: TypedContractEvent<
      SignerUpdatedEvent.InputTuple,
      SignerUpdatedEvent.OutputTuple,
      SignerUpdatedEvent.OutputObject
    >;
  };
}
