/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockSlashingCoordinatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canSlashOperator"
      | "getSlashedAmount"
      | "setCanSlash"
      | "slashOperator"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OperatorSlashed"): EventFragment;

  encodeFunctionData(
    functionFragment: "canSlashOperator",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSlashedAmount",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCanSlash",
    values: [AddressLike, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "slashOperator",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "canSlashOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSlashedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCanSlash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashOperator",
    data: BytesLike
  ): Result;
}

export namespace OperatorSlashedEvent {
  export type InputTuple = [
    operator: AddressLike,
    avsId: BytesLike,
    slashedAmount: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    avsId: string,
    slashedAmount: bigint
  ];
  export interface OutputObject {
    operator: string;
    avsId: string;
    slashedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockSlashingCoordinator extends BaseContract {
  connect(runner?: ContractRunner | null): MockSlashingCoordinator;
  waitForDeployment(): Promise<this>;

  interface: MockSlashingCoordinatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canSlashOperator: TypedContractMethod<
    [operator: AddressLike, avsId: BytesLike],
    [boolean],
    "view"
  >;

  getSlashedAmount: TypedContractMethod<
    [operator: AddressLike, avsId: BytesLike],
    [bigint],
    "view"
  >;

  setCanSlash: TypedContractMethod<
    [operator: AddressLike, avsId: BytesLike, canSlash: boolean],
    [void],
    "nonpayable"
  >;

  slashOperator: TypedContractMethod<
    [operator: AddressLike, avsId: BytesLike, slashingParams: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canSlashOperator"
  ): TypedContractMethod<
    [operator: AddressLike, avsId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSlashedAmount"
  ): TypedContractMethod<
    [operator: AddressLike, avsId: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setCanSlash"
  ): TypedContractMethod<
    [operator: AddressLike, avsId: BytesLike, canSlash: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slashOperator"
  ): TypedContractMethod<
    [operator: AddressLike, avsId: BytesLike, slashingParams: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OperatorSlashed"
  ): TypedContractEvent<
    OperatorSlashedEvent.InputTuple,
    OperatorSlashedEvent.OutputTuple,
    OperatorSlashedEvent.OutputObject
  >;

  filters: {
    "OperatorSlashed(address,bytes32,uint256)": TypedContractEvent<
      OperatorSlashedEvent.InputTuple,
      OperatorSlashedEvent.OutputTuple,
      OperatorSlashedEvent.OutputObject
    >;
    OperatorSlashed: TypedContractEvent<
      OperatorSlashedEvent.InputTuple,
      OperatorSlashedEvent.OutputTuple,
      OperatorSlashedEvent.OutputObject
    >;
  };
}
