/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface UMAAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "assertionSubmitted"
      | "assertionToRequest"
      | "getAssertionId"
      | "getRequestId"
      | "handleAssertion"
      | "requestToAssertion"
      | "submitOutcomeToUMA"
      | "umaOracle"
      | "veyraOracleAVS"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssertionHandled"
      | "OutcomeSubmitted"
      | "UMAAssertionCreated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assertionSubmitted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assertionToRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssertionId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleAssertion",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestToAssertion",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitOutcomeToUMA",
    values: [
      BytesLike,
      BytesLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "umaOracle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "veyraOracleAVS",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assertionSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assertionToRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssertionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleAssertion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestToAssertion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitOutcomeToUMA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "umaOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "veyraOracleAVS",
    data: BytesLike
  ): Result;
}

export namespace AssertionHandledEvent {
  export type InputTuple = [
    assertionId: BytesLike,
    requestId: BytesLike,
    claim: BytesLike
  ];
  export type OutputTuple = [
    assertionId: string,
    requestId: string,
    claim: string
  ];
  export interface OutputObject {
    assertionId: string;
    requestId: string;
    claim: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OutcomeSubmittedEvent {
  export type InputTuple = [
    assertionId: BytesLike,
    requestId: BytesLike,
    outcome: boolean
  ];
  export type OutputTuple = [
    assertionId: string,
    requestId: string,
    outcome: boolean
  ];
  export interface OutputObject {
    assertionId: string;
    requestId: string;
    outcome: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UMAAssertionCreatedEvent {
  export type InputTuple = [
    newAssertionId: BytesLike,
    originalAssertionId: BytesLike,
    outcome: boolean
  ];
  export type OutputTuple = [
    newAssertionId: string,
    originalAssertionId: string,
    outcome: boolean
  ];
  export interface OutputObject {
    newAssertionId: string;
    originalAssertionId: string;
    outcome: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UMAAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): UMAAdapter;
  waitForDeployment(): Promise<this>;

  interface: UMAAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  assertionSubmitted: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  assertionToRequest: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getAssertionId: TypedContractMethod<[requestId: BytesLike], [string], "view">;

  getRequestId: TypedContractMethod<[assertionId: BytesLike], [string], "view">;

  handleAssertion: TypedContractMethod<
    [assertionId: BytesLike, claim: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;

  requestToAssertion: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  submitOutcomeToUMA: TypedContractMethod<
    [
      requestId: BytesLike,
      claim: BytesLike,
      liveness: BigNumberish,
      currency: AddressLike,
      bond: BigNumberish,
      identifier: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  umaOracle: TypedContractMethod<[], [string], "view">;

  veyraOracleAVS: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assertionSubmitted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "assertionToRequest"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAssertionId"
  ): TypedContractMethod<[requestId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRequestId"
  ): TypedContractMethod<[assertionId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "handleAssertion"
  ): TypedContractMethod<
    [assertionId: BytesLike, claim: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestToAssertion"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "submitOutcomeToUMA"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      claim: BytesLike,
      liveness: BigNumberish,
      currency: AddressLike,
      bond: BigNumberish,
      identifier: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "umaOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "veyraOracleAVS"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AssertionHandled"
  ): TypedContractEvent<
    AssertionHandledEvent.InputTuple,
    AssertionHandledEvent.OutputTuple,
    AssertionHandledEvent.OutputObject
  >;
  getEvent(
    key: "OutcomeSubmitted"
  ): TypedContractEvent<
    OutcomeSubmittedEvent.InputTuple,
    OutcomeSubmittedEvent.OutputTuple,
    OutcomeSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "UMAAssertionCreated"
  ): TypedContractEvent<
    UMAAssertionCreatedEvent.InputTuple,
    UMAAssertionCreatedEvent.OutputTuple,
    UMAAssertionCreatedEvent.OutputObject
  >;

  filters: {
    "AssertionHandled(bytes32,bytes32,bytes)": TypedContractEvent<
      AssertionHandledEvent.InputTuple,
      AssertionHandledEvent.OutputTuple,
      AssertionHandledEvent.OutputObject
    >;
    AssertionHandled: TypedContractEvent<
      AssertionHandledEvent.InputTuple,
      AssertionHandledEvent.OutputTuple,
      AssertionHandledEvent.OutputObject
    >;

    "OutcomeSubmitted(bytes32,bytes32,bool)": TypedContractEvent<
      OutcomeSubmittedEvent.InputTuple,
      OutcomeSubmittedEvent.OutputTuple,
      OutcomeSubmittedEvent.OutputObject
    >;
    OutcomeSubmitted: TypedContractEvent<
      OutcomeSubmittedEvent.InputTuple,
      OutcomeSubmittedEvent.OutputTuple,
      OutcomeSubmittedEvent.OutputObject
    >;

    "UMAAssertionCreated(bytes32,bytes32,bool)": TypedContractEvent<
      UMAAssertionCreatedEvent.InputTuple,
      UMAAssertionCreatedEvent.OutputTuple,
      UMAAssertionCreatedEvent.OutputObject
    >;
    UMAAssertionCreated: TypedContractEvent<
      UMAAssertionCreatedEvent.InputTuple,
      UMAAssertionCreatedEvent.OutputTuple,
      UMAAssertionCreatedEvent.OutputObject
    >;
  };
}
