/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAllocationManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAVSId"
      | "getAVSOperators"
      | "isOperatorRegisteredToAVS"
      | "optInToAVS"
      | "optOutOfAVS"
      | "registerAVS"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAVSId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAVSOperators",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperatorRegisteredToAVS",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "optInToAVS",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "optOutOfAVS",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAVS",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getAVSId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAVSOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperatorRegisteredToAVS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "optInToAVS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "optOutOfAVS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAVS",
    data: BytesLike
  ): Result;
}

export interface IAllocationManager extends BaseContract {
  connect(runner?: ContractRunner | null): IAllocationManager;
  waitForDeployment(): Promise<this>;

  interface: IAllocationManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAVSId: TypedContractMethod<[avsAddress: AddressLike], [string], "view">;

  getAVSOperators: TypedContractMethod<[avsId: BytesLike], [string[]], "view">;

  isOperatorRegisteredToAVS: TypedContractMethod<
    [operator: AddressLike, avsId: BytesLike],
    [boolean],
    "view"
  >;

  optInToAVS: TypedContractMethod<[avsId: BytesLike], [void], "nonpayable">;

  optOutOfAVS: TypedContractMethod<[avsId: BytesLike], [void], "nonpayable">;

  registerAVS: TypedContractMethod<
    [metadataURI: string, slashingParams: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAVSId"
  ): TypedContractMethod<[avsAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAVSOperators"
  ): TypedContractMethod<[avsId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isOperatorRegisteredToAVS"
  ): TypedContractMethod<
    [operator: AddressLike, avsId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "optInToAVS"
  ): TypedContractMethod<[avsId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "optOutOfAVS"
  ): TypedContractMethod<[avsId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerAVS"
  ): TypedContractMethod<
    [metadataURI: string, slashingParams: BytesLike],
    [string],
    "nonpayable"
  >;

  filters: {};
}
