/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGnosisConditionalTokens } from "./IGnosisConditionalTokens";
export type { IUMAOptimisticOracle } from "./IUMAOptimisticOracle";
export type { IVPOAdapter } from "./IVPOAdapter";
export type { IVPOOracle } from "./IVPOOracle";
