/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IUMAOptimisticOracleInterface extends Interface {
  getFunction(
    nameOrSignature: "assertTruth" | "getAssertion"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AssertionMade" | "AssertionSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assertTruth",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssertion",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "assertTruth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssertion",
    data: BytesLike
  ): Result;
}

export namespace AssertionMadeEvent {
  export type InputTuple = [
    assertionId: BytesLike,
    claim: BytesLike,
    asserter: AddressLike,
    callbackRecipient: AddressLike,
    escalationManager: AddressLike,
    liveness: BigNumberish,
    currency: AddressLike,
    bond: BigNumberish,
    identifier: BytesLike
  ];
  export type OutputTuple = [
    assertionId: string,
    claim: string,
    asserter: string,
    callbackRecipient: string,
    escalationManager: string,
    liveness: bigint,
    currency: string,
    bond: bigint,
    identifier: string
  ];
  export interface OutputObject {
    assertionId: string;
    claim: string;
    asserter: string;
    callbackRecipient: string;
    escalationManager: string;
    liveness: bigint;
    currency: string;
    bond: bigint;
    identifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssertionSettledEvent {
  export type InputTuple = [assertionId: BytesLike, resolution: boolean];
  export type OutputTuple = [assertionId: string, resolution: boolean];
  export interface OutputObject {
    assertionId: string;
    resolution: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IUMAOptimisticOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IUMAOptimisticOracle;
  waitForDeployment(): Promise<this>;

  interface: IUMAOptimisticOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assertTruth: TypedContractMethod<
    [
      claim: BytesLike,
      asserter: AddressLike,
      callbackRecipient: AddressLike,
      escalationManager: AddressLike,
      liveness: BigNumberish,
      currency: AddressLike,
      bond: BigNumberish,
      identifier: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  getAssertion: TypedContractMethod<
    [assertionId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        asserter: string;
        claim: string;
        callbackRecipient: string;
        escalationManager: string;
        liveness: bigint;
        currency: string;
        bond: bigint;
        identifier: string;
        settled: boolean;
        settlementResolution: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assertTruth"
  ): TypedContractMethod<
    [
      claim: BytesLike,
      asserter: AddressLike,
      callbackRecipient: AddressLike,
      escalationManager: AddressLike,
      liveness: BigNumberish,
      currency: AddressLike,
      bond: BigNumberish,
      identifier: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAssertion"
  ): TypedContractMethod<
    [assertionId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        asserter: string;
        claim: string;
        callbackRecipient: string;
        escalationManager: string;
        liveness: bigint;
        currency: string;
        bond: bigint;
        identifier: string;
        settled: boolean;
        settlementResolution: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AssertionMade"
  ): TypedContractEvent<
    AssertionMadeEvent.InputTuple,
    AssertionMadeEvent.OutputTuple,
    AssertionMadeEvent.OutputObject
  >;
  getEvent(
    key: "AssertionSettled"
  ): TypedContractEvent<
    AssertionSettledEvent.InputTuple,
    AssertionSettledEvent.OutputTuple,
    AssertionSettledEvent.OutputObject
  >;

  filters: {
    "AssertionMade(bytes32,bytes,address,address,address,uint64,address,uint256,bytes32)": TypedContractEvent<
      AssertionMadeEvent.InputTuple,
      AssertionMadeEvent.OutputTuple,
      AssertionMadeEvent.OutputObject
    >;
    AssertionMade: TypedContractEvent<
      AssertionMadeEvent.InputTuple,
      AssertionMadeEvent.OutputTuple,
      AssertionMadeEvent.OutputObject
    >;

    "AssertionSettled(bytes32,bool)": TypedContractEvent<
      AssertionSettledEvent.InputTuple,
      AssertionSettledEvent.OutputTuple,
      AssertionSettledEvent.OutputObject
    >;
    AssertionSettled: TypedContractEvent<
      AssertionSettledEvent.InputTuple,
      AssertionSettledEvent.OutputTuple,
      AssertionSettledEvent.OutputObject
    >;
  };
}
