/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IVeyraOracleAVSInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "finalizeResolution"
      | "fulfillVerification"
      | "getFulfillment"
      | "requestResolution"
      | "submitAttestation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AVSNodeUpdated"
      | "AttestationSubmitted"
      | "OperatorWeightUpdated"
      | "ProofVerificationFailed"
      | "QuorumReached"
      | "QuorumThresholdUpdated"
      | "ResolutionFinalized"
      | "VerificationFulfilled"
      | "VerificationRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "finalizeResolution",
    values: [BytesLike, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillVerification",
    values: [BytesLike, BytesLike, boolean, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFulfillment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestResolution",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAttestation",
    values: [BytesLike, boolean, BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "finalizeResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fulfillVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFulfillment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAttestation",
    data: BytesLike
  ): Result;
}

export namespace AVSNodeUpdatedEvent {
  export type InputTuple = [node: AddressLike, enabled: boolean];
  export type OutputTuple = [node: string, enabled: boolean];
  export interface OutputObject {
    node: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttestationSubmittedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    operator: AddressLike,
    outcome: boolean,
    attestationCid: BytesLike,
    signature: BytesLike
  ];
  export type OutputTuple = [
    requestId: string,
    operator: string,
    outcome: boolean,
    attestationCid: string,
    signature: string
  ];
  export interface OutputObject {
    requestId: string;
    operator: string;
    outcome: boolean;
    attestationCid: string;
    signature: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorWeightUpdatedEvent {
  export type InputTuple = [operator: AddressLike, weight: BigNumberish];
  export type OutputTuple = [operator: string, weight: bigint];
  export interface OutputObject {
    operator: string;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofVerificationFailedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    operator: AddressLike,
    proof: BytesLike
  ];
  export type OutputTuple = [
    requestId: string,
    operator: string,
    proof: string
  ];
  export interface OutputObject {
    requestId: string;
    operator: string;
    proof: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuorumReachedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    outcome: boolean,
    totalWeight: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    outcome: boolean,
    totalWeight: bigint
  ];
  export interface OutputObject {
    requestId: string;
    outcome: boolean;
    totalWeight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuorumThresholdUpdatedEvent {
  export type InputTuple = [threshold: BigNumberish];
  export type OutputTuple = [threshold: bigint];
  export interface OutputObject {
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionFinalizedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    outcome: boolean,
    aggregateSignature: BytesLike,
    totalWeight: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    outcome: boolean,
    aggregateSignature: string,
    totalWeight: bigint
  ];
  export interface OutputObject {
    requestId: string;
    outcome: boolean;
    aggregateSignature: string;
    totalWeight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationFulfilledEvent {
  export type InputTuple = [
    requestId: BytesLike,
    attestationCid: BytesLike,
    outcome: boolean,
    metadata: BytesLike
  ];
  export type OutputTuple = [
    requestId: string,
    attestationCid: string,
    outcome: boolean,
    metadata: string
  ];
  export interface OutputObject {
    requestId: string;
    attestationCid: string;
    outcome: boolean;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRequestedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    requester: AddressLike,
    marketRef: BytesLike,
    data: BytesLike
  ];
  export type OutputTuple = [
    requestId: string,
    requester: string,
    marketRef: string,
    data: string
  ];
  export interface OutputObject {
    requestId: string;
    requester: string;
    marketRef: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IVeyraOracleAVS extends BaseContract {
  connect(runner?: ContractRunner | null): IVeyraOracleAVS;
  waitForDeployment(): Promise<this>;

  interface: IVeyraOracleAVSInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  finalizeResolution: TypedContractMethod<
    [requestId: BytesLike, outcome: boolean, aggregateSignature: BytesLike],
    [void],
    "nonpayable"
  >;

  fulfillVerification: TypedContractMethod<
    [
      requestId: BytesLike,
      attestationCid: BytesLike,
      outcome: boolean,
      metadata: BytesLike,
      timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFulfillment: TypedContractMethod<
    [requestId: BytesLike],
    [
      [boolean, string, boolean, string] & {
        exists: boolean;
        attestationCid: string;
        outcome: boolean;
        metadata: string;
      }
    ],
    "view"
  >;

  requestResolution: TypedContractMethod<
    [marketRef: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;

  submitAttestation: TypedContractMethod<
    [
      requestId: BytesLike,
      outcome: boolean,
      attestationCid: BytesLike,
      signature: BytesLike,
      proof: BytesLike,
      timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "finalizeResolution"
  ): TypedContractMethod<
    [requestId: BytesLike, outcome: boolean, aggregateSignature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fulfillVerification"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      attestationCid: BytesLike,
      outcome: boolean,
      metadata: BytesLike,
      timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getFulfillment"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [
      [boolean, string, boolean, string] & {
        exists: boolean;
        attestationCid: string;
        outcome: boolean;
        metadata: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestResolution"
  ): TypedContractMethod<
    [marketRef: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitAttestation"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      outcome: boolean,
      attestationCid: BytesLike,
      signature: BytesLike,
      proof: BytesLike,
      timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AVSNodeUpdated"
  ): TypedContractEvent<
    AVSNodeUpdatedEvent.InputTuple,
    AVSNodeUpdatedEvent.OutputTuple,
    AVSNodeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AttestationSubmitted"
  ): TypedContractEvent<
    AttestationSubmittedEvent.InputTuple,
    AttestationSubmittedEvent.OutputTuple,
    AttestationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorWeightUpdated"
  ): TypedContractEvent<
    OperatorWeightUpdatedEvent.InputTuple,
    OperatorWeightUpdatedEvent.OutputTuple,
    OperatorWeightUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProofVerificationFailed"
  ): TypedContractEvent<
    ProofVerificationFailedEvent.InputTuple,
    ProofVerificationFailedEvent.OutputTuple,
    ProofVerificationFailedEvent.OutputObject
  >;
  getEvent(
    key: "QuorumReached"
  ): TypedContractEvent<
    QuorumReachedEvent.InputTuple,
    QuorumReachedEvent.OutputTuple,
    QuorumReachedEvent.OutputObject
  >;
  getEvent(
    key: "QuorumThresholdUpdated"
  ): TypedContractEvent<
    QuorumThresholdUpdatedEvent.InputTuple,
    QuorumThresholdUpdatedEvent.OutputTuple,
    QuorumThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionFinalized"
  ): TypedContractEvent<
    ResolutionFinalizedEvent.InputTuple,
    ResolutionFinalizedEvent.OutputTuple,
    ResolutionFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationFulfilled"
  ): TypedContractEvent<
    VerificationFulfilledEvent.InputTuple,
    VerificationFulfilledEvent.OutputTuple,
    VerificationFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRequested"
  ): TypedContractEvent<
    VerificationRequestedEvent.InputTuple,
    VerificationRequestedEvent.OutputTuple,
    VerificationRequestedEvent.OutputObject
  >;

  filters: {
    "AVSNodeUpdated(address,bool)": TypedContractEvent<
      AVSNodeUpdatedEvent.InputTuple,
      AVSNodeUpdatedEvent.OutputTuple,
      AVSNodeUpdatedEvent.OutputObject
    >;
    AVSNodeUpdated: TypedContractEvent<
      AVSNodeUpdatedEvent.InputTuple,
      AVSNodeUpdatedEvent.OutputTuple,
      AVSNodeUpdatedEvent.OutputObject
    >;

    "AttestationSubmitted(bytes32,address,bool,bytes,bytes)": TypedContractEvent<
      AttestationSubmittedEvent.InputTuple,
      AttestationSubmittedEvent.OutputTuple,
      AttestationSubmittedEvent.OutputObject
    >;
    AttestationSubmitted: TypedContractEvent<
      AttestationSubmittedEvent.InputTuple,
      AttestationSubmittedEvent.OutputTuple,
      AttestationSubmittedEvent.OutputObject
    >;

    "OperatorWeightUpdated(address,uint256)": TypedContractEvent<
      OperatorWeightUpdatedEvent.InputTuple,
      OperatorWeightUpdatedEvent.OutputTuple,
      OperatorWeightUpdatedEvent.OutputObject
    >;
    OperatorWeightUpdated: TypedContractEvent<
      OperatorWeightUpdatedEvent.InputTuple,
      OperatorWeightUpdatedEvent.OutputTuple,
      OperatorWeightUpdatedEvent.OutputObject
    >;

    "ProofVerificationFailed(bytes32,address,bytes)": TypedContractEvent<
      ProofVerificationFailedEvent.InputTuple,
      ProofVerificationFailedEvent.OutputTuple,
      ProofVerificationFailedEvent.OutputObject
    >;
    ProofVerificationFailed: TypedContractEvent<
      ProofVerificationFailedEvent.InputTuple,
      ProofVerificationFailedEvent.OutputTuple,
      ProofVerificationFailedEvent.OutputObject
    >;

    "QuorumReached(bytes32,bool,uint256)": TypedContractEvent<
      QuorumReachedEvent.InputTuple,
      QuorumReachedEvent.OutputTuple,
      QuorumReachedEvent.OutputObject
    >;
    QuorumReached: TypedContractEvent<
      QuorumReachedEvent.InputTuple,
      QuorumReachedEvent.OutputTuple,
      QuorumReachedEvent.OutputObject
    >;

    "QuorumThresholdUpdated(uint256)": TypedContractEvent<
      QuorumThresholdUpdatedEvent.InputTuple,
      QuorumThresholdUpdatedEvent.OutputTuple,
      QuorumThresholdUpdatedEvent.OutputObject
    >;
    QuorumThresholdUpdated: TypedContractEvent<
      QuorumThresholdUpdatedEvent.InputTuple,
      QuorumThresholdUpdatedEvent.OutputTuple,
      QuorumThresholdUpdatedEvent.OutputObject
    >;

    "ResolutionFinalized(bytes32,bool,bytes,uint256)": TypedContractEvent<
      ResolutionFinalizedEvent.InputTuple,
      ResolutionFinalizedEvent.OutputTuple,
      ResolutionFinalizedEvent.OutputObject
    >;
    ResolutionFinalized: TypedContractEvent<
      ResolutionFinalizedEvent.InputTuple,
      ResolutionFinalizedEvent.OutputTuple,
      ResolutionFinalizedEvent.OutputObject
    >;

    "VerificationFulfilled(bytes32,bytes,bool,bytes)": TypedContractEvent<
      VerificationFulfilledEvent.InputTuple,
      VerificationFulfilledEvent.OutputTuple,
      VerificationFulfilledEvent.OutputObject
    >;
    VerificationFulfilled: TypedContractEvent<
      VerificationFulfilledEvent.InputTuple,
      VerificationFulfilledEvent.OutputTuple,
      VerificationFulfilledEvent.OutputObject
    >;

    "VerificationRequested(bytes32,address,bytes32,bytes)": TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
    VerificationRequested: TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
  };
}
