/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IVPOAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "fulfillVerification"
      | "getFulfillment"
      | "requestVerification"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "VerificationFulfilled" | "VerificationRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "fulfillVerification",
    values: [BytesLike, BytesLike, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFulfillment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestVerification",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "fulfillVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFulfillment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestVerification",
    data: BytesLike
  ): Result;
}

export namespace VerificationFulfilledEvent {
  export type InputTuple = [
    requestId: BytesLike,
    attestationCid: BytesLike,
    outcome: boolean,
    metadata: BytesLike
  ];
  export type OutputTuple = [
    requestId: string,
    attestationCid: string,
    outcome: boolean,
    metadata: string
  ];
  export interface OutputObject {
    requestId: string;
    attestationCid: string;
    outcome: boolean;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRequestedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    requester: AddressLike,
    marketRef: BytesLike,
    data: BytesLike
  ];
  export type OutputTuple = [
    requestId: string,
    requester: string,
    marketRef: string,
    data: string
  ];
  export interface OutputObject {
    requestId: string;
    requester: string;
    marketRef: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IVPOAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): IVPOAdapter;
  waitForDeployment(): Promise<this>;

  interface: IVPOAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fulfillVerification: TypedContractMethod<
    [
      requestId: BytesLike,
      attestationCid: BytesLike,
      outcome: boolean,
      metadata: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFulfillment: TypedContractMethod<
    [requestId: BytesLike],
    [
      [boolean, string, boolean, string] & {
        exists: boolean;
        attestationCid: string;
        outcome: boolean;
        metadata: string;
      }
    ],
    "view"
  >;

  requestVerification: TypedContractMethod<
    [marketRef: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fulfillVerification"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      attestationCid: BytesLike,
      outcome: boolean,
      metadata: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getFulfillment"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [
      [boolean, string, boolean, string] & {
        exists: boolean;
        attestationCid: string;
        outcome: boolean;
        metadata: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestVerification"
  ): TypedContractMethod<
    [marketRef: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "VerificationFulfilled"
  ): TypedContractEvent<
    VerificationFulfilledEvent.InputTuple,
    VerificationFulfilledEvent.OutputTuple,
    VerificationFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRequested"
  ): TypedContractEvent<
    VerificationRequestedEvent.InputTuple,
    VerificationRequestedEvent.OutputTuple,
    VerificationRequestedEvent.OutputObject
  >;

  filters: {
    "VerificationFulfilled(bytes32,bytes,bool,bytes)": TypedContractEvent<
      VerificationFulfilledEvent.InputTuple,
      VerificationFulfilledEvent.OutputTuple,
      VerificationFulfilledEvent.OutputObject
    >;
    VerificationFulfilled: TypedContractEvent<
      VerificationFulfilledEvent.InputTuple,
      VerificationFulfilledEvent.OutputTuple,
      VerificationFulfilledEvent.OutputObject
    >;

    "VerificationRequested(bytes32,address,bytes32,bytes)": TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
    VerificationRequested: TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
  };
}
