/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAllocationManager,
  IAllocationManagerInterface,
} from "../../../contracts/interfaces/IAllocationManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "avsAddress",
        type: "address",
      },
    ],
    name: "getAVSId",
    outputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "getAVSOperators",
    outputs: [
      {
        internalType: "address[]",
        name: "operators",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "isOperatorRegisteredToAVS",
    outputs: [
      {
        internalType: "bool",
        name: "isRegistered",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "optInToAVS",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "optOutOfAVS",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "metadataURI",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "slashingParams",
        type: "bytes",
      },
    ],
    name: "registerAVS",
    outputs: [
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAllocationManager__factory {
  static readonly abi = _abi;
  static createInterface(): IAllocationManagerInterface {
    return new Interface(_abi) as IAllocationManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAllocationManager {
    return new Contract(address, _abi, runner) as unknown as IAllocationManager;
  }
}
