/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDelegationManager,
  IDelegationManagerInterface,
} from "../../../contracts/interfaces/IDelegationManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "getOperatorShares",
    outputs: [
      {
        internalType: "uint256",
        name: "totalShares",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "isOperator",
    outputs: [
      {
        internalType: "bool",
        name: "isRegistered",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "avs",
        type: "address",
      },
    ],
    name: "operatorShares",
    outputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDelegationManager__factory {
  static readonly abi = _abi;
  static createInterface(): IDelegationManagerInterface {
    return new Interface(_abi) as IDelegationManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDelegationManager {
    return new Contract(address, _abi, runner) as unknown as IDelegationManager;
  }
}
