/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVPOAdapter__factory } from "./IVPOAdapter__factory";
export { IVPOOracle__factory } from "./IVPOOracle__factory";
