/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISlashingCoordinator,
  ISlashingCoordinatorInterface,
} from "../../../contracts/interfaces/ISlashingCoordinator";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "slashedAmount",
        type: "uint256",
      },
    ],
    name: "OperatorSlashed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
    ],
    name: "canSlashOperator",
    outputs: [
      {
        internalType: "bool",
        name: "canSlash",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "avsId",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "slashingParams",
        type: "bytes",
      },
    ],
    name: "slashOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISlashingCoordinator__factory {
  static readonly abi = _abi;
  static createInterface(): ISlashingCoordinatorInterface {
    return new Interface(_abi) as ISlashingCoordinatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISlashingCoordinator {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISlashingCoordinator;
  }
}
