/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUMAOptimisticOracle,
  IUMAOptimisticOracleInterface,
} from "../../../contracts/interfaces/IUMAOptimisticOracle";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "assertionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "claim",
        type: "bytes",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asserter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "callbackRecipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "escalationManager",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "liveness",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "address",
        name: "currency",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "bond",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "identifier",
        type: "bytes32",
      },
    ],
    name: "AssertionMade",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "assertionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "resolution",
        type: "bool",
      },
    ],
    name: "AssertionSettled",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "claim",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "asserter",
        type: "address",
      },
      {
        internalType: "address",
        name: "callbackRecipient",
        type: "address",
      },
      {
        internalType: "address",
        name: "escalationManager",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "liveness",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "currency",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "bond",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "identifier",
        type: "bytes32",
      },
    ],
    name: "assertTruth",
    outputs: [
      {
        internalType: "bytes32",
        name: "assertionId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "assertionId",
        type: "bytes32",
      },
    ],
    name: "getAssertion",
    outputs: [
      {
        internalType: "address",
        name: "asserter",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "claim",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "callbackRecipient",
        type: "address",
      },
      {
        internalType: "address",
        name: "escalationManager",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "liveness",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "currency",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "bond",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "identifier",
        type: "bytes32",
      },
      {
        internalType: "bool",
        name: "settled",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "settlementResolution",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IUMAOptimisticOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IUMAOptimisticOracleInterface {
    return new Interface(_abi) as IUMAOptimisticOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUMAOptimisticOracle {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IUMAOptimisticOracle;
  }
}
